name: GLOW
on:
  push:
    branches:
      - main
jobs:
  DOC-DEPLOY:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name : Run scripts
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Build
      uses: ./.github/my-action
      env:
        ACCESS_TOKEN: ${{ secrets.MY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
        BASE_BRANCH: main
