name: GLOW
on:
  push:
    branches:
      - main
jobs:
  DOC-DEPLOY:
    name: doc-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: echo --
        run: echo hello world
        run: git branch

      # - name: Run build
      #   uses: ./.github/action-deploy-doc
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.MY_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: build
      #     BUILD_SCRIPT: npm install && npm run build
